### PR TITLE
Bootcamp: Kiran

### PR DESCRIPTION
**Pull request by kiransuren**
First run through of the bootcamp

### CODE REVIEW

**Comment by heyitslu** [comment]
Good first pass! You some of got the basics - the component meets the input(kinda)/output voltage and current reqs, and you have the main component values down. Here are some comment:

- Digikey says that the input voltage range is 4-16V for LT1507, but the datasheet says the range is actually 4-15V, so beware!!! In retrospect, it would have been better to filter with min input <4V and max input >16V so that you include parts that not only meet, but exceed the 4-16V input range requirement. The increased selection probably would have given you a cheaper buck and/or one that is easier to implement. The calculation may be annoying to do, but if I were you I would have picked a buck with an adjustable output and figured out the feedback resistor values. 
- I thought the BOOST pin was used if you wanted to use LT1507 in boost mode (low input V to high output V), but that is **not** the case. Ilooks like this is a weird buck with a boost pin/section used to improve the efficiency (see p 5 of datasheet for quick desc of BOOST pin function, and p. 13 for how to choose the cap and catch diode). If you want to stick with this component, you will have to implement this section.
- Do you have a part number for L3 and C20? L3 Selection is important to ensure that the buck can handle the 1A output current requirement. p. 9-11 of the datasheet gives some info regarding how to pick L3 and C20, suggesting specific brands as well. 
- Put some input capacitors on the VBAT rail near the VIN pin to smooth out any spikes/valleys caused by varying load on the battery. While the datasheet suggests _tantalum_ caps for the output (which is kind of weird), _ceramic_ caps should be used on the input. See p. 14


- For buck layout, its important to keep any high-frequency trace lengths as short as possible. This means traces connected to the VSW and BOOST pins need to be short. For example, if you moved C20 to directly south of U3 you shorten the trace going to VSW already. The input caps (once you add them) should be close to Vin pin as well. 
- The layout seems to have 2 C20s? Also I can't find C19 on the schematic, it's only on the layout? You may want to remove these extra footprints. 
- This isn't really something that needs to be changed, but I thought I'd mention it anyway: routing traditionally avoids right angles when possible. This is a rule remnant of old times when PCB manufacturing didn't like right angles (The acids used to etch traces risked collecting in sharp corners) that still applies in very specific ultra high frequency applications (>1Ghz)
image

**Comment by kiransuren** [comment]
Thanks for the review @heyitslu ! So I found a new component which I think is better suited (cheaper) and I think I've met all the requirements https://www.semicon.sanken-ele.co.jp/sk_content/si-8033jd_ds_en.pdf. Also I tried calculating the values of the external parts required but I'm not to sure if they're correct. This is what I got:
Cin -> 33µF and allowable ripple current  > 0.4A
Cout -> 68µF and allowable ripple current > 0.4A
D1 -> Handle up to 2A (some leeway from 1.5A) and up to 20V (leeway from 16V)
L1 -> 68µH

**Comment by heyitslu** [comment]
The calculations look good! Since it's just the bootcamp you can go ahead and implement the circuit - I have some comments as to why this design wouldn't fly normally though. Some tips:
- Note that when selecting Cin and Cout, ESR and rated voltage matter as well - capacitance tends to decrease as voltage approaches a C's rated voltage, so you may want to nearly double your rated voltage (ex: 16V input max -> 25/35/50V rated Voltaged for cap). 
- When picking an inductor, manufacturers will try to trick you and say the rated current is some value (like 2A). But what you want is to make sure is it has high enough **saturated** current, as that's when inductance starts to drop significantly. So watch out for that! Rated current will typically be larger than saturated current.

Some notes for next time:
- The part still doesn't meet the 4-16V input req - for future designs make sure to meet all specifications, we can't have a system not functioning at an expected input voltage!
- From the part's footprint and the calculated inductance, the part chosen will likely result in a physically large design - this is typically undesirable. However, there were no size constraints for the bootcamp so in this case it's all good.

Go ahead and pick some parts!

**Comment by kiransuren** [comment]
Awesome thanks for the notes! Yeah I realized I really can't trust the digikey filter, even after specifically asking for a minimum of 4 or below it still gave me something higher. I'm guessing tho the spec sheet will always be the best source of truth when it comes to it huh?

**Comment by kiransuren** [comment]
Also since this regulator has 43V input max, would it make any difference that the input in our case is a lot less (for example, would the regulator be less more or efficient?)

**Comment by heyitslu** [comment]
Yep haha, alwayyyys check the datasheet

**Comment by kiransuren** [comment]
@heyitslu Second version of bootcamp updated, using new regulator that meets the requirements https://www.diodes.com/assets/Datasheets/AP63200-AP63201-AP63203-AP63205.pdf

**Pull request closed without merging**
