### PR TITLE
USB Interface

### PR DESCRIPTION
**Pull request by jetkov**
Added the FT4232H Quad USB to UART/MPSSE IC to program the safety and pilot controllers with SWD as well as interface with their UART debug channels. Programming and debug operations can then be performed using one USB connection to a PC.

### CODE REVIEW

**Comment by scholvat** [comment]
Looks really good. There is a lot of datasheet to read over so I'll try to look a bit more into it, but the few obvious things I see are listed below:

**Comment by scholvat** [comment]
It looks ready good. There is a lot of datasheet to read over, but I'll mention a few things that stand out to me:
-Have a hierachechal pin for VBUS, since that will be used in the power supply circuit. Don't bother routing it on the main page, we'll deal with that later.
-The crystal is missing a part number field, the rest of them look good though

I'll look over it more on Monday night, but at a cursory glance it looks like you did a great job with this.

**Comment by eterrestrial** [comment]
Heyo, looks good, you just have a handful of connection errors cause KiCAD can be dumb and it can be hard to align some stuff. There are also some hierarchical label mismatches, basically just make sure the names of the labels you place on the main sheet match up with what you put on the usb sheet. Use the electrical rules checker for a list of the errors though you're going to have to annotate first so, in the usb interface sheet, go to tools->annotate schematic. You're going to have to annotate all since there are some test points in hardware.sch that aren't annotated. Then run the electrical rules checker. Fix the connections, then go to the annotator and remove the annotations for only the usb sheet.

**Comment by eterrestrial** [comment]
That's hot.

**Pull request merged**
