### PR TITLE
Bootcamp: Alex Petkovic

### PR DESCRIPTION
**Pull request by jetkov**
Replaced the 3.3V linear regulator with a buck regulator.

### CODE REVIEW

**Comment by scholvat** [comment]
Hi Alex- your part looks like a good choice with a nice and simple external circuit. However, I think you might need to look at your inductor again. You are using the same footprint that was used for the 4.7uH inductor, and the 47uH inductor required for that regulator will be much larger. You'll need to find the part number and footprint for the proper inductor and add that to the circuit.

**Comment by jetkov** [comment]
Hi Stephen, I found a 47uH inductor in the same series as the 4.7uH inductor with the same package and good specs, so I just added it to the component_library.csv, and modified the 5.1x6.5.kicad_mod footprint file property naming to be compatible with both. I've pushed these to my fork of the WARG-KiCAD Repo.

**Comment by scholvat** [comment]
Unfortunately the 47uH inductor you chose can only handle 2A saturation, which just isn't enough to handle the inrush current on the rising edge of the PWM signal. Buck regulator inductors generally have a safety margin of x2 to avoid saturation since that is approximately how much the inrush current will be to charge the output capacitors.

**Comment by scholvat** [comment]
Reading over the data sheet, they seem to spec a max current output of 3A, so get an inductor that matches that spec.

**Comment by jetkov** [comment]
Hi Stephen, thanks for the guidance. Please see the latest commits, with the replacement inductor and the footprint I made for it.

**Comment by scholvat** [comment]
Looks almost good, one small issue. Your PCB layout has a large trace for the feedback node (3V3_JMP), but  your switching node (pin 1 of the inductor) is where all the current is going through. I would advise dipping the 3.3V through a via, and keeping the switching node on layer 1.

**Comment by scholvat** [comment]
Looks good 👍 I'll add you to Asana

**Pull request closed without merging**
