### PR TITLE
IMU Bodge Board

### PR DESCRIPTION
**Pull request by MarkDunk**
Fixes footprint mismatch

### CODE REVIEW

**Review by Fberbari — APPROVED** [review]
I've checked the mappings of the new pads to the old pads, that the board fits on our main board, and that the resistor/cap footprints lineup with the ones on the main board. All looks good.

Only concern is with soldering... We gonna be able to properly reflow the stuff under the middle of the board ? Maybe that's a cross that bridge when we come to it thing.

**Comment by MarkDunk** [comment]
Can either use this: https://www.digikey.com/en/products/detail/mg-chemicals/8331-14G/2639875 or I could get some high temp resin from formlabs.

**Comment by Fberbari** [comment]
What if you added a via from the pads to the top of the board. Thing we could touch it with an iron and reflow that way ?

**Comment by MarkDunk** [comment]
So attach the chip to the new board and then use the vias to solder the board to zeropilot? Or the other way around?

**Comment by Fberbari** [comment]
I'm thinking we could put paste down on the pads of zeropilot, lay your new board on top of it, then use the vias to stick our iron in and solder down pad by pad. Then after its soldered we could solder the chip.

Though tbh I think its something we'll be able to figure out. May aswell buy that chemical you mentioned since we're planning on doing a digikey order though.

**Comment by MarkDunk** [comment]
Ok, I see what you mean. Only 6 pins on the 4x4 lga need to be soldered, the rest are power and ground which can come from the caps. I'll update the design.

**Comment by Fberbari** [comment]
Yep, looks good

**Review by heyitslu — APPROVED** [review]
Forgot to merge

**Pull request merged**
